### ISSUE TITLE
--hist does not work

### ISSUE THREAD

**Issue by pe7ro** [pe7ro/dr14meter#1]
```
$ dr14meter --hist 02.flac

/02.flac

Start histogram:
Track Title: Breathe
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/dr14meter/__main__.py", line 28, in <module>
    main()
  File "/dr14meter/__main__.py", line 24, in main
    dr14.main()
  File "/dr14meter/dr14_tmeter.py", line 135, in main
    if run_analysis_opt(options, path_name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dr14meter/dr14_utils.py", line 240, in run_analysis_opt
    hist.compute_track(path_name)
  File "/dr14meter/audio_analysis.py", line 58, in compute_track
    self.virt_compute()
  File "/dr14meter/audio_analysis.py", line 102, in virt_compute
    compute_hist(at.Y, at.Fs, self.getDuration(), title=title)
  File "/dr14meter/dr_histogram.py", line 74, in compute_hist
    (hist, bin_edges, patches) = pyplot.hist(rms, 100, normed=True)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 3236, in hist
    return gca().hist(
           ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 1469, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 7015, in hist
    p._internal_update(kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 1219, in _internal_update
    return self._update_props(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 1193, in _update_props
    raise AttributeError(
AttributeError: Rectangle.set() got an unexpected keyword argument 'normed'
```

**Comment by pe7ro** [comment]
Part of https://github.com/simon-r/dr14_t.meter/issues/66
